backend: clean
	go get -u github.com/valyala/fasthttp
	go get -u github.com/buaazp/fasthttprouter
	go get -u github.com/AubSs/fasthttplogger
	go get -u github.com/lab259/cors
	go get -u github.com/lib/pq
	go get -u github.com/jinzhu/gorm/dialects/postgres
	go get -u github.com/PuerkitoBio/goquery
	go get -u github.com/likexian/whois-go
	go build

clean:
	rm -f backend